name: 'Run .NET Reactor'
description: 'Downloads, extracts, and runs .NET Reactor based on the runner OS.'
author: 'Daniel Bunting'
branding:
  icon: 'lock'
  color: 'blue'
inputs:
  project_file:
    description: 'Path to the .NET Reactor project file.'
    required: true
  input_path:
    description: 'Input path of the .NET assembly to obfuscate.'
    required: true
  output_path:
    description: 'Output path for the obfuscated .NET assembly.'
    required: true
  license_file:
    description: 'Path to the license file. Optional.'
    required: false
  additional_params:
    description: 'Additional command line parameters for .NET Reactor. Optional.'
    required: false
  version:
    description: 'Version of the .NET Reactor to use, defaults to Latest.'
    required: false
    default: 'latest'

runs:
  using: "composite"
  steps:
    - name: Download .NET Reactor
      run: |
        if [ "${{ runner.os }}" = "Windows" ]; then
          powershell -Command "if (-Not (Test-Path './dotnet-reactor/dotNET_Reactor.Console.exe')) { Invoke-WebRequest 'https://raw.githubusercontent.com/eziriz/ReactorAction/main/versions/windows_${{ inputs.version }}.zip' -OutFile 'dotNetReactor.zip' }"
        elif [ "${{ runner.os }}" = "Linux" ]; then
          if [ ! -f "./dotnet-reactor/dotNET_Reactor" ]; then
            curl -L "https://raw.githubusercontent.com/eziriz/ReactorAction/main/versions/linux_${{ inputs.version }}.zip" -o dotNetReactor.zip
          fi
        elif [ "${{ runner.os }}" = "macOS" ]; then
          if [ ! -f "./dotnet-reactor/dotNET_Reactor" ]; then
            curl -L "https://raw.githubusercontent.com/eziriz/ReactorAction/main/versions/macos_${{ inputs.version }}.zip" -o dotNetReactor.zip
          fi
        fi
      shell: bash

    - name: Extract .NET Reactor
      run: |
        if [ "${{ runner.os }}" = "Windows" ]; then
          powershell -Command "if (-Not (Test-Path './dotnet-reactor/dotNET_Reactor.Console.exe')) { Expand-Archive 'dotNetReactor.zip' -DestinationPath './dotnet-reactor' }"
          powershell -Command "Copy-Item '$GITHUB_WORKSPACE/${{ inputs.license_file }}' -Destination './dotnet-reactor/'"
        elif [ "${{ runner.os }}" = "Linux" ] || [ "${{ runner.os }}" = "macOS" ]; then
          if [ ! -f "./dotnet-reactor/dotNET_Reactor" ]; then
            unzip dotNetReactor.zip -d dotnet-reactor
          fi
          if [ -n "${{ inputs.license_file }}" ] && [ "${{ inputs.license_file }}" != "" ]; then
            cp "$GITHUB_WORKSPACE/${{ inputs.license_file }}" ./dotnet-reactor/
          fi
        fi
      shell: bash

    - name: Execute .NET Reactor
      run: |
        if [ "${{ runner.os }}" = "Windows" ]; then
          "./dotnet-reactor/dotNET_Reactor.Console.exe" -file "$GITHUB_WORKSPACE/${{ inputs.input_path }}" -project "$GITHUB_WORKSPACE/${{ inputs.project_file }}" -targetfile "$GITHUB_WORKSPACE/${{ inputs.output_path }}" ${{ inputs.additional_params }}
        elif [ "${{ runner.os }}" = "Linux" ]; then
          chmod +x "./dotnet-reactor/dotNET_Reactor"
          "./dotnet-reactor/dotNET_Reactor" -file "$GITHUB_WORKSPACE/${{ inputs.input_path }}" -project "$GITHUB_WORKSPACE/${{ inputs.project_file }}" -targetfile "$GITHUB_WORKSPACE/${{ inputs.output_path }}" ${{ inputs.additional_params }}
        elif [ "${{ runner.os }}" = "macOS" ]; then
          chmod +x "./dotnet-reactor/dotNET_Reactor"
          "./dotnet-reactor/dotNET_Reactor" -file "$GITHUB_WORKSPACE/${{ inputs.input_path }}" -project "$GITHUB_WORKSPACE/${{ inputs.project_file }}" -targetfile "$GITHUB_WORKSPACE/${{ inputs.output_path }}" ${{ inputs.additional_params }}
        fi
      shell: bash
