name: 'Run dotNET Reactor'
description: 'Downloads, extracts, and runs dotNET Reactor based on the runner OS.'
inputs:
  project_file:
    description: 'Path to the dotNET Reactor project file.'
    required: true
  input_path:
    description: 'Input path of the .NET assembly to obfuscate.'
    required: true
  output_path:
    description: 'Output path for the obfuscated .NET assembly.'
    required: true
  license_file:
    description: 'Path to the license file.'
    required: true 

runs:
  using: "composite"
  steps:
    - name: Download dotNET Reactor
      run: |
        if [ "${{ runner.os }}" = "Windows" ]; then
          powershell -Command "if (-Not (Test-Path './dotnet-reactor/dotNET_Reactor.Console.exe')) { Invoke-WebRequest 'https://raw.githubusercontent.com/DanielBunting/ReactorObfuscation/main/dotnet-reactor/windows/dotNetReactor.zip' -OutFile 'dotNetReactor.zip' }"
        elif [ "${{ runner.os }}" = "Linux" ]; then
          if [ ! -f "./dotnet-reactor/dotNET_Reactor" ]; then
            curl -L "https://raw.githubusercontent.com/DanielBunting/ReactorObfuscation/main/dotnet-reactor/linux/dotNET_Reactor.zip" -o dotNetReactor.zip
          fi
        elif [ "${{ runner.os }}" = "macOS" ]; then
          if [ ! -f "./dotnet-reactor/dotNET_Reactor" ]; then
            curl -L "https://raw.githubusercontent.com/DanielBunting/ReactorObfuscation/main/dotnet-reactor/macos/dotNET_Reactor.zip" -o dotNetReactor.zip
          fi
        fi
      shell: bash

    - name: Extract dotNET Reactor
      run: |
        if [ "${{ runner.os }}" = "Windows" ]; then
          powershell -Command "if (-Not (Test-Path './dotnet-reactor/dotNET_Reactor.Console.exe')) { Expand-Archive 'dotNetReactor.zip' -DestinationPath './dotnet-reactor' }"
          powershell -Command "Copy-Item '${{ inputs.license_file }}' -Destination './dotnet-reactor/'"
        elif [ "${{ runner.os }}" = "Linux" ] || [ "${{ runner.os }}" = "macOS" ]; then
          if [ ! -f "./dotnet-reactor/dotNET_Reactor" ]; then
            unzip dotNetReactor.zip -d dotnet-reactor
          fi
          cp "$GITHUB_WORKSPACE/${{ inputs.license_file }}" ./dotnet-reactor/
        fi
      shell: bash

    - name: Execute dotNET Reactor
      run: |
        if [ "${{ runner.os }}" = "Windows" ]; then
          "./dotnet-reactor/dotNET_Reactor.Console.exe" -file "$GITHUB_WORKSPACE/${{ inputs.input_path }}" -project "$GITHUB_WORKSPACE/${{ inputs.project_file }}" -targetfile "$GITHUB_WORKSPACE/${{ inputs.output_path }}"
        elif [ "${{ runner.os }}" = "Linux" ]; then
          chmod +x "./dotnet-reactor/dotNET_Reactor"
          "./dotnet-reactor/dotNET_Reactor" -file "$GITHUB_WORKSPACE/${{ inputs.input_path }}" -project "$GITHUB_WORKSPACE/${{ inputs.project_file }}" -targetfile "$GITHUB_WORKSPACE/${{ inputs.output_path }}"
        elif [ "${{ runner.os }}" = "macOS" ]; then
          chmod +x "./dotnet-reactor/dotNET_Reactor"
          "./dotnet-reactor/dotNET_Reactor" -file "$GITHUB_WORKSPACE/${{ inputs.input_path }}" -project "$GITHUB_WORKSPACE/${{ inputs.project_file }}" -targetfile "$GITHUB_WORKSPACE/${{ inputs.output_path }}"
        fi
      shell: bash
